name: Docker Semoss Builds and Push Docker Image to Quay
on:
  push:
    branches-ignore:
      - "**" # This effectively excludes the workflow from running on push events
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

jobs:
    cuda12-5-py-build-and-push:
        runs-on: self-hosted
        steps:
          - name: cuda 12.5 py Docker Build
            run: |
              export DOCKER_TLS_CERTDIR=""
              rm -rf docker-semoss || true
              git clone https://github.com/SEMOSS/docker-semoss.git
              cd docker-semoss
              git checkout cuda12.5-py   
              echo ${{ secrets.CI_REGISTRY_PASSWORD}} | docker login ${{ vars.CI_REGISTRY }} -u ${{ secrets.CI_REGISTRY_USER}} --password-stdin
              docker build . -t ${{ vars.CI_REGISTRY }}/semoss/docker:cuda12.5-py
              docker push  ${{ vars.CI_REGISTRY }}/semoss/docker:cuda12.5-py