name: Schedule workflows on Other Branches
on:
  push:
    branches-ignore:
      - "**" # This effectively excludes the workflow from running on push events
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:
jobs:
  docker-semoss-builds:
    runs-on: self-hosted
    permissions:
      contents: read
      actions: write # Grant write permissions to GITHUB_TOKEN for actions
    strategy:
      matrix:
        branch: ['debian11', 'cuda12.2', 'ubi8-rhel', 'cuda12.5-py']

    steps:
      - name: checkout ${{ matrix.branch }} branch
        uses: actions/checkout@v4
        with:
          ref: ${{ matrix.branch }}
      
      - name: commit on ${{ matrix.branch }}
        run: |
          echo "triggered at ${date}" > trigger.txt
          git add trigger.txt
          git commit -m "Trigger workflow via commit [skip ci]"
          git push
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}
