name: Schedule workflows on Other Branches
on:
  push:
    branches-ignore:
      - "**" # This effectively excludes the workflow from running on push events
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:
jobs:
  ubi8-build-and-push:
    runs-on: self-hosted
    permissions:
      contents: read
      actions: write # Grant write permissions to GITHUB_TOKEN for actions

    steps:
      - name: Authenticate gh CLI
        run: gh auth login --with-token <<< "${{ secrets.PAT_TOKEN }}"

      - name: Trigger workflow on debian11 Branch
        run: gh workflow run 'debian11-workflow.yml' --ref debian11
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}

      - name: Trigger workflow on cuda12.2 Branch
        run: gh workflow run 'cuda12.2-workflow.yml' --ref cuda12.2
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}

      - name: Trigger workflow on cuda12.5-py Branch
        run: gh workflow run 'cuda12.5-py-workflow.yml' --ref cuda12.5-py
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}

      - name: Trigger workflow on ubi8-rhel Branch
        run: gh workflow run 'ubi8-rhel-workflow.yml' --ref ubi8-rhel
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}