name: Schedule workflows on Other Branches
on:
  push:
    branches-ignore:
      - "**" # This effectively excludes the workflow from running on push events
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:
jobs:
  docker-semoss-builds:
    runs-on: self-hosted
    permissions:
      contents: write
    strategy:
      matrix:
        branch: ['debian11', 'cuda12.2', 'ubi8-rhel', 'cuda12.5-py']

    steps:
      - name: checkout ${{ matrix.branch }} branch
        uses: actions/checkout@v4
        with:
          ref: ${{ matrix.branch }}
          persist-credentials: false # Disable default GITHUB_TOKEN credentials

      - name: Set up Git Authentication
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/SEMOSS/docker-semoss.git

      - name: configure Git
        run: |
          git config --global user.name "${{ vars.USER_NAME }}"
          git config --global user.email "${{ vars.USER_EMAIL }}"

      - name: commit on ${{ matrix.branch }}
        run: |
          echo "triggered at $(date +'%Y-%m-%dT%H:%M:%S')" > trigger.txt
          git add trigger.txt
          git commit -m "Trigger workflow via commit"
          git push origin HEAD:${{ matrix.branch }}
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
