name: ubi8-rhel Build and Push Docker Image to Quay
on:
  push:
    branches-ignore:
      - "**" # This effectively excludes the workflow from running on push events
  schedule:
    - cron: "15 2 * * *"
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Docker Build
        run: |
          export DOCKER_TLS_CERTDIR=""
          ls -lah
          pwd
          echo ${{ secrets.CI_REGISTRY_PASSWORD}} | docker login ${{ vars.CI_REGISTRY }} -u ${{ secrets.CI_REGISTRY_USER}} --password-stdin
          docker build . -t ${{ vars.CI_REGISTRY }}/semoss/docker:ubi8-rhel
          docker push  ${{ vars.CI_REGISTRY }}/semoss/docker:ubi8-rhel