name: Ubi8-rhel workflow
on:
  push:
    branches:
      - cuda12.5-py
    branches-ignore:
      - "**" # This effectively excludes the workflow from running on push events
  workflow_dispatch:

jobs:
    ubi8-build-and-push:
        runs-on: self-hosted
        steps:
          - name: ubi8 Docker Build
            run: |
              export DOCKER_TLS_CERTDIR=""
              rm -rf docker-semoss || true
              git clone https://github.com/SEMOSS/docker-semoss.git
              cd docker-semoss
              git checkout ubi8-rhel
              echo ${{ secrets.CI_REGISTRY_PASSWORD}} | docker login ${{ vars.CI_REGISTRY }} -u ${{ secrets.CI_REGISTRY_USER}} --password-stdin
              docker build . -t ${{ vars.CI_REGISTRY }}/semoss/docker:ubi8-rhel
              docker push  ${{ vars.CI_REGISTRY }}/semoss/docker:ubi8-rhel